name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # ---------------------------
    # Checkout Project Code
    # ---------------------------
    - name: Checkout Code
      uses: actions/checkout@v3

    # ---------------------------
    # GHCR Login (Important!)
    # ---------------------------
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CAR_PAT }}

    # ---------------------------
    # Build Docker Image
    # ---------------------------
    - name: Build Docker Image
      run: |
        docker build -t ghcr.io/sncharanraj/devops-app:latest .

    # ---------------------------
    # Push Docker Image to GHCR
    # ---------------------------
    - name: Push Image
      run: |
        docker push ghcr.io/sncharanraj/devops-app:latest

    # ---------------------------
    # Deploy to Ubuntu VM via SSH
    # ---------------------------
    - name: Deploy to VM via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          docker pull ghcr.io/sncharanraj/devops-app:latest
          docker stop devops-app || true
          docker rm devops-app || true
          docker run -d --name devops-app -p 5000:5000 ghcr.io/sncharanraj/devops-app:latest
